## Design-guide

/design-guide:
  controller: Main
  action: designGuide
  roles: []

## Main

/:
  controller: Main
  action: home
  roles: []

/contact:
  controller: Main
  action: contact
  roles: []

/login:
  controller: Security
  action: login
  roles: []

/logout:
  controller: Security
  action: logout
  roles: [admin,viewer,chef]

/register:
  controller: Security
  action: register
  roles: []

/password-forgot:
  controller: Security
  action: passwordForgot
  roles: []

/enable-account:
  controller: Security
  action: enableAccount
  roles: []

/change-password:
  controller: Security
  action: changePassword
  roles: []

## Admin
/admin:
  controller: Dashboard
  action: dashboard
  roles: [admin]

/admin/dashboard:
  controller: Dashboard
  action: dashboard
  roles: [admin]

/admin/menus:
  controller: Menu
  action: showMenus
  roles: [admin]

/admin/menus/add:
  controller: Menu
  action: addMenu
  roles: [admin]

/admin/recipes:
  controller: Recipe
  action: showRecipes
  roles: [admin]

/admin/recipes/add:
  controller: Recipe
  action: addRecipe
  roles: [admin]
  
/admin/recipes/delete:
  controller: Recipe
  action: deleteRecipe
  roles: [admin]
  
/admin/recipes/edit:
  controller: Recipe
  action: editRecipe
  roles: [admin]

/admin/users:
  controller: User
  action: showUsers
  roles: [admin]

/admin/reviews:
  controller: Review
  action: showReviews
  roles: [admin]

/admin/pages:
  controller: PageController
  action: showPages
  roles: [admin]

/admin/pages/edit-page/{id}:
  controller: PageController
  action: editPage
  roles: [admin]

/admin/category/add:
  controller: Category
  action: addCategorie
  roles: [admin]

/admin/category:
  controller: Category
  action: showCategories
  roles: [admin]

/admin/category/delete:
  controller: Category
  action: deleteCategory
  roles: [admin]

/admin/category/edit:
  controller: Category
  action: editCategory
/admin/pages/add-page:
  controller: PageController
  action: addPage
  roles: [admin]