## Design-guide

/design-guide:
  controller: Main
  action: designGuide
  roles: []

## Main

/:
  controller: Main
  action: home
  roles: []

/contact:
  controller: Main
  action: contact
  roles: []

/login:
  controller: Security
  action: login
  roles: []

/logout:
  controller: Security
  action: logout
  roles: [admin,viewer,chef]

/register:
  controller: Security
  action: register
  roles: []

/password-forgot:
  controller: Security
  action: passwordForgot
  roles: []

/enable-account:
  controller: Security
  action: enableAccount
  roles: []

/change-password:
  controller: Security
  action: changePassword
  roles: []

## Admin
/admin:
  controller: Dashboard
  action: dashboard
  roles: [admin]

/admin/dashboard:
  controller: Dashboard
  action: dashboard
  roles: [admin]

/admin/menus:
  controller: Menu
  action: showMenus
  roles: [admin]

/admin/recipies:
  controller: Recipe
  action: showRecipies
  roles: [admin]

/admin/users:
  controller: User
  action: showUsers
  roles: [admin]

/admin/reviews:
  controller: Review
  action: showReviews
  roles: [admin]

/admin/pages:
  controller: PageController
  action: showPages
  roles: [admin]

/admin/pages/edit-page/{id}:
  controller: Page
  action: editPage
  roles: [admin]