## Main

/:
  controller: Main
  action: home
  roles: []

/login:
  controller: Security
  action: login
  roles: []

/logout:
  controller: Security
  action: logout
  roles: [admin,viewer,chef]

/register:
  controller: Security
  action: register
  roles: []

/password-forgot:
  controller: Security
  action: passwordForgot
  roles: []

/enable-account:
  controller: Security
  action: enableAccount
  roles: []

/change-password:
  controller: Security
  action: changePassword
  roles: []

## Admin
/admin:
  controller: Dashboard
  action: dashboard
  roles: [admin]

/admin/dashboard:
  controller: Dashboard
  action: dashboard
  roles: [admin]

/admin/menus:
  controller: Menu
  action: showMenus
  roles: [admin]

/admin/recipes:
  controller: Recipe
  action: showRecipes
  roles: [admin]

/admin/recipes/add:
  controller: Recipe
  action: addRecipe
  roles: [admin]

/admin/users:
  controller: User
  action: showUsers
  roles: [admin]

/admin/reviews:
  controller: Review
  action: showReviews
  roles: [admin]
